#include <iostream>
#include <fstream>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <conio.h>
#include "arrays.hpp"
#include "formaters.hpp"
#include "manager.hpp"
#include "student.hpp"
#include "project.hpp"
#include "individual.hpp"
#include "group.hpp"